
SQLALCHEMY_ECHO = True

SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:TSjinrong@172.16.48.69/post_op'

SQLALCHEMY_TRACK_MODIFICATIONS = False

SQLALCHEMY_ENCODING = "utf8mb4"

SQLALCHEMY_POOL_TIMEOUT = 15

SQLALCHEMY_POOL_RECYCLE = 2

APP_SECRET_KEY = 'zach.wang'